# name of your action
name: CAST Highlight Scan

branding:
  icon: "code"
  color: "yellow"

description: Run CAST Highlight scans on your code to get Software Intelligence insights (vulnerabilities, cloud readiness, etc.)

# action triggers, here every two weeks (days 5 and 15 of the month) at 6am
on:
  
  workflow_dispatch:
    branches: [ main ]




jobs:
  scan:
    runs-on: ubuntu-latest
    # use the prod environment, where the secret CAST_HIGHLIGHT_API_TOKEN is defined
    environment: prod

    steps:
      - uses: actions/checkout@v2

      - name: get company and application ids
        run: |
          cat .github/workflows/hl.env >> $GITHUB_ENV
      - name: scan project source code 
        run: |
          docker run --rm -v $(pwd):/s -v /tmp:/w  casthighlight/hl-agent-cli \
                                                   sourceDir /s \
                                                   workingDir /w \
                                                   tokenAuth ${{ secrets.af7114f9-df8f-4ccc-915b-bf7ce2f5daa7}} \
                                                   companyId ${{ env.18601 }} \
                                                   applicationId ${{ env.122700 }} \
                                                   serverUrl ${{ env.https://rpa.casthighlight.com }} \
                                                   --ignoreDirectories ${{ env.ignoreDirectories }}